version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     ports:
       - "33062:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - ./db:/docker-entrypoint-initdb.d/:ro

   small_backend:
     depends_on:
     - db
     image: python:latest
     ports:
     - "8000:80"
     restart: always
